// 各种类型的开局

export const test = [
  [
    {name: 'zhangfei', id: 1},
    {name: 'huangzhong', id: 1},
    {name: 'zhaoyun', id: 1},
    {name: 'machao', id: 1}
  ],
  [
    {name: 'zhangfei', id: 2},
    {name: 'huangzhong', id: 2},
    {name: 'zhaoyun', id: 2},
    {name: 'machao', id: 2}
  ],
  [
    {name: 'bing', id: 1},
    {name: 'bing', id: 2},
    {name: 'guanyu', id: 1},
    {name: 'guanyu', id: 2},
  ],
  [
    {name: 'caocao', id: 1},
    {name: 'caocao', id: 2},
    null,
    {name: 'bing', id: 3},
  ],
  [
    {name: 'caocao', id: 3},
    {name: 'caocao', id: 4},
    null,
    {name: 'bing', id: 4},
  ]
]

// 横刀立马
export const hengDaoLiMa = [
  [
    {name: 'zhangfei', id: 1},
    {name: 'caocao', id: 1},
    {name: 'caocao', id: 2},
    {name: 'zhaoyun', id: 1}
  ],
  [
    {name: 'zhangfei', id: 2},
    {name: 'caocao', id: 3},
    {name: 'caocao', id: 4},
    {name: 'zhaoyun', id: 2},
  ],
  [
    {name: 'machao', id: 1},
    {name: 'guanyu', id: 1},
    {name: 'guanyu', id: 2},
    {name: 'huangzhong', id: 1},
  ],
  [
    {name: 'machao', id: 2},
    {name: 'bing', id: 2},
    {name: 'bing', id: 3},
    {name: 'huangzhong', id: 2},
  ],
  [
    {name: 'bing', id: 1},
    null,
    null,
    {name: 'bing', id: 4},
  ]
]

export const showHowSteps = [
  {name: 'bing', id: 4, moveDirection: 'left'},
  {name: 'huangzhong', id: 2, moveDirection: 'bottom'},
  {name: 'guanyu', id: 2, moveDirection: 'right'},
  {name: 'bing', id: 2, moveDirection: 'bottom'},
  {name: 'machao', id: 2, moveDirection: 'right'},
  {name: 'bing', id: 1, moveDirection: 'top'},
  {name: 'bing', id: 2, moveDirection: 'left'},
  {name: 'machao', id: 2, moveDirection: 'bottom'},
  {name: 'guanyu', id: 2, moveDirection: 'left'},
  {name: 'guanyu', id: 2, moveDirection: 'left'},
  {name: 'bing', id: 3, moveDirection: 'top'},
  {name: 'bing', id: 3, moveDirection: 'right'},
  {name: 'bing', id: 4, moveDirection: 'top'},
  {name: 'bing', id: 4, moveDirection: 'top'},
  {name: 'machao', id: 2, moveDirection: 'right'},
  {name: 'bing', id: 1, moveDirection: 'right'},
  {name: 'bing', id: 1, moveDirection: 'bottom'},
  {name: 'guanyu', id: 2, moveDirection: 'bottom'},
  {name: 'bing', id: 4, moveDirection: 'left'},
  {name: 'bing', id: 4, moveDirection: 'left'},
  {name: 'bing', id: 3, moveDirection: 'left'},
  {name: 'bing', id: 3, moveDirection: 'left'},
  {name: 'huangzhong', id: 2, moveDirection: 'top'},
  {name: 'machao', id: 2, moveDirection: 'top'},
  {name: 'bing', id: 1, moveDirection: 'right'},
  {name: 'bing', id: 1, moveDirection: 'right'},
  {name: 'bing', id: 2, moveDirection: 'right'},
  {name: 'bing', id: 2, moveDirection: 'right'},
  {name: 'guanyu', id: 2, moveDirection: 'bottom'},
  {name: 'bing', id: 3, moveDirection: 'bottom'},
  {name: 'bing', id: 3, moveDirection: 'left'},
  {name: 'machao', id: 2, moveDirection: 'left'},
  {name: 'huangzhong', id: 2, moveDirection: 'left'},
  {name: 'zhaoyun', id: 2, moveDirection: 'bottom'},
  {name: 'zhaoyun', id: 2, moveDirection: 'bottom'},
  {name: 'caocao', id: 2, moveDirection: 'right'},
  {name: 'zhangfei', id: 2, moveDirection: 'right'},
  {name: 'bing', id: 4, moveDirection: 'top'},
  {name: 'bing', id: 4, moveDirection: 'top'},
  {name: 'bing', id: 3, moveDirection: 'top'},
  {name: 'bing', id: 3, moveDirection: 'top'},
  {name: 'machao', id: 2, moveDirection: 'left'},
  {name: 'zhangfei', id: 2, moveDirection: 'bottom'},
  {name: 'zhangfei', id: 2, moveDirection: 'bottom'},
  {name: 'caocao', id: 2, moveDirection: 'left'},
  {name: 'zhaoyun', id: 2, moveDirection: 'top'},
  {name: 'zhaoyun', id: 2, moveDirection: 'top'},
  {name: 'huangzhong', id: 2, moveDirection: 'right'},
  {name: 'bing', id: 2, moveDirection: 'top'},
  {name: 'bing', id: 2, moveDirection: 'top'},
  {name: 'bing', id: 1, moveDirection: 'left'},
  {name: 'bing', id: 1, moveDirection: 'top'},
  {name: 'guanyu', id: 2, moveDirection: 'right'},
  {name: 'guanyu', id: 2, moveDirection: 'right'},
  {name: 'zhangfei', id: 2, moveDirection: 'bottom'},
  {name: 'machao', id: 2, moveDirection: 'bottom'},
  {name: 'bing', id: 2, moveDirection: 'left'},
  {name: 'bing', id: 2, moveDirection: 'left'},
  {name: 'caocao', id: 2, moveDirection: 'bottom'},
  {name: 'bing', id: 4, moveDirection: 'right'},
  {name: 'bing', id: 4, moveDirection: 'right'},
  {name: 'bing', id: 3, moveDirection: 'top'},
  {name: 'bing', id: 3, moveDirection: 'right'},
  {name: 'bing', id: 2, moveDirection: 'top'},
  {name: 'bing', id: 2, moveDirection: 'top'},
  {name: 'machao', id: 2, moveDirection: 'top'},
  {name: 'machao', id: 2, moveDirection: 'top'},
  {name: 'zhangfei', id: 2, moveDirection: 'left'},
  {name: 'bing', id: 1, moveDirection: 'left'},
  {name: 'bing', id: 1, moveDirection: 'bottom'},
  {name: 'caocao', id: 2, moveDirection: 'bottom'},
  {name: 'bing', id: 4, moveDirection: 'bottom'},
  {name: 'bing', id: 4, moveDirection: 'left'},
  {name: 'zhaoyun', id: 2, moveDirection: 'left'},
  {name: 'huangzhong', id: 2, moveDirection: 'top'},
  {name: 'huangzhong', id: 2, moveDirection: 'top'},
  {name: 'caocao', id: 2, moveDirection: 'right'},
  {name: 'bing', id: 4, moveDirection: 'bottom'},
  {name: 'bing', id: 4, moveDirection: 'bottom'},
  {name: 'bing', id: 3, moveDirection: 'bottom'},
  {name: 'bing', id: 2, moveDirection: 'right'},
  {name: 'machao', id: 2, moveDirection: 'top'},
  {name: 'zhangfei', id: 2, moveDirection: 'top'},
  {name: 'bing', id: 1, moveDirection: 'left'},
  {name: 'bing', id: 4, moveDirection: 'bottom'},
  {name: 'caocao', id: 2, moveDirection: 'left'},
  {name: 'huangzhong', id: 2, moveDirection: 'bottom'},
  {name: 'huangzhong', id: 2, moveDirection: 'bottom'},
  {name: 'zhaoyun', id: 2, moveDirection: 'right'},
  {name: 'bing', id: 2, moveDirection: 'right'},
  {name: 'bing', id: 3, moveDirection: 'right'},
  {name: 'machao', id: 2, moveDirection: 'right'},
  {name: 'zhangfei', id: 2, moveDirection: 'top'},
  {name: 'zhangfei', id: 2, moveDirection: 'top'},
  {name: 'caocao', id: 2, moveDirection: 'left'},
  {name: 'bing', id: 3, moveDirection: 'bottom'},
  {name: 'bing', id: 3, moveDirection: 'bottom'},
  {name: 'bing', id: 2, moveDirection: 'bottom'},
  {name: 'bing', id: 2, moveDirection: 'bottom'},
  {name: 'zhaoyun', id: 2, moveDirection: 'left'},
  {name: 'huangzhong', id: 2, moveDirection: 'top'},
  {name: 'huangzhong', id: 2, moveDirection: 'top'},
  {name: 'bing', id: 3, moveDirection: 'right'},
  {name: 'bing', id: 3, moveDirection: 'top'},
  {name: 'guanyu', id: 2, moveDirection: 'top'},
  {name: 'bing', id: 4, moveDirection: 'right'},
  {name: 'bing', id: 4, moveDirection: 'right'},
  {name: 'bing', id: 1, moveDirection: 'right'},
  {name: 'bing', id: 1, moveDirection: 'right'},
  {name: 'caocao', id: 2, moveDirection: 'bottom'},
  {name: 'bing', id: 2, moveDirection: 'left'},
  {name: 'bing', id: 2, moveDirection: 'left'},
  {name: 'bing', id: 3, moveDirection: 'left'},
  {name: 'bing', id: 3, moveDirection: 'left'},
  {name: 'guanyu', id: 2, moveDirection: 'top'},
  {name: 'bing', id: 1, moveDirection: 'top'},
  {name: 'bing', id: 1, moveDirection: 'right'},
  {name: 'caocao', id: 2, moveDirection: 'right'},
]